wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.5
    t:
      1:
      - 1
      - 3
      2:
      - 1
      - 3
      3:
      - 2
      4: 3.9.5
      5: 0.10.32
      8:
      - 1
      - 5
