wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.5
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.9.5
      5: 0.10.32
      8:
      - 1
      - 5
data_test_path:
  desc: null
  value: ./Data/Testing
data_train_path:
  desc: null
  value: ./Data/Training
device:
  desc: null
  value: cuda
epochs:
  desc: null
  value: 4
heat_layers:
  desc: null
  value:
  - 2
heatmap_batch_size:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.0001
model_name:
  desc: null
  value: vgg19
occlusion_size:
  desc: null
  value:
  - 60
  - 60
shuffle_data:
  desc: null
  value: true
train_batch_size:
  desc: null
  value: 200
